# Generated by Django 2.0.1 on 2018-01-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventCategory',
            new_name='EventType',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
