# Generated by Django 2.0.1 on 2018-01-31 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event_platform.UploadedImage'),
        ),
    ]
