# Generated by Django 2.0.1 on 2018-01-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='content',
        ),
    ]
