# Generated by Django 2.0.1 on 2018-01-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0002_remove_feedback_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='content',
            field=models.TextField(default='wow'),
            preserve_default=False,
        ),
    ]
