# Generated by Django 2.0.1 on 2018-01-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0002_event_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='description',
        ),
    ]
