# Generated by Django 2.0.1 on 2018-01-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0003_feedback_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
    ]
