# Generated by Django 2.0.1 on 2018-02-04 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0004_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='img',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_platform.UploadedImage'),
            preserve_default=False,
        ),
    ]
