# Generated by Django 2.0.1 on 2018-01-16 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0005_auto_20180116_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_event_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_event_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
