# Generated by Django 2.0.1 on 2018-02-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0005_eventtype_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='portrait',
        ),
    ]
