# Generated by Django 2.0.1 on 2018-01-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0005_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='notify',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='receive',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='recommend',
        ),
    ]
