# Generated by Django 2.0.1 on 2018-02-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0006_remove_user_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_platform.UploadedImage'),
            preserve_default=False,
        ),
    ]
