# Generated by Django 2.0.1 on 2018-01-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0006_auto_20180116_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
