# Generated by Django 2.0.1 on 2018-01-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0007_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
