# Generated by Django 2.0.1 on 2018-02-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0007_user_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
