# Generated by Django 2.0.1 on 2018-01-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0008_auto_20180129_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='receive',
            field=models.IntegerField(default=1),
        ),
    ]
