# Generated by Django 2.0.1 on 2018-02-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0008_auto_20180204_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_platform.UploadedImage'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_platform.UploadedImage'),
        ),
    ]
