# Generated by Django 2.0.1 on 2018-01-21 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0009_auto_20180118_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('target_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('recommend', models.IntegerField(default=1)),
                ('notify', models.IntegerField(default=1)),
                ('receive', models.IntegerField(default=1)),
            ],
        ),
    ]
