# Generated by Django 2.0.1 on 2018-01-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0009_auto_20180118_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
