# Generated by Django 2.0.1 on 2018-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0009_systemconfig_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='notify',
            field=models.IntegerField(default=1),
        ),
    ]
