# Generated by Django 2.0.1 on 2018-02-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0010_auto_20180207_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='is_show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='is_show_events',
            field=models.BooleanField(default=False),
        ),
    ]
