# Generated by Django 2.0.1 on 2018-01-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0010_uploadedimage'),
        ('event_platform', '0010_systemconfig'),
    ]

    operations = [
    ]
