# Generated by Django 2.0.1 on 2018-02-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0011_auto_20180207_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_platform.UploadedImage'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_platform.UploadedImage'),
        ),
    ]
