# Generated by Django 2.0.1 on 2018-01-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0011_merge_20180122_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
