# Generated by Django 2.0.1 on 2018-02-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0012_auto_20180208_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_url',
            field=models.TextField(),
        ),
    ]
