# Generated by Django 2.0.1 on 2018-02-08 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0013_auto_20180208_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_platform.UploadedImage'),
        ),
    ]
