# Generated by Django 2.0.1 on 2018-01-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0010_systemconfig_notify'),
        ('event_platform', '0014_auto_20180129_0320'),
    ]

    operations = [
    ]
