# Generated by Django 2.0.1 on 2018-02-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0013_auto_20180207_2007'),
        ('event_platform', '0014_auto_20180208_1025'),
    ]

    operations = [
    ]
