# Generated by Django 2.0.1 on 2018-01-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0017_user_system_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenVerificationPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('verification_code', models.CharField(max_length=5)),
            ],
        ),
    ]
